[providers]
  nodejs = "22"

[phases.setup]
  nixPkgs = ["nodejs-22_x", "npm-10_x"]

[phases.install]
  cmds = ["npm ci --only=production --no-optional --prefer-offline --maxsockets=1"]

[phases.build]
  cmds = ["npm run build"]

[start]
  cmd = "npx serve -s build -l ${PORT:-3000} -H 0.0.0.0"

[variables]
  NODE_ENV = "production"
  REACT_APP_API_BASE_URL = "https://policyradar-backend-production.up.railway.app/api"
  NODE_OPTIONS = "--max-old-space-size=512"
  NPM_CONFIG_MAXSOCKETS = "1"