version: '3.8'

services:
  policy-radar:
    build: .
    ports:
      - "8001:8001"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - DATA_DIR=./data
      - VECTORS_DIR=./vectors
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080,https://your-domain.com
      - LOG_LEVEL=info
    volumes:
      - ./data:/app/data:ro
      - ./vectors:/app/vectors:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - policy-radar
    restart: unless-stopped

volumes:
  data:
  vectors: