providers = ["node"]

[variables]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://policyradar-backend-production.up.railway.app/api"
  NODE_OPTIONS = "--max-old-space-size=2048"  # Increased memory
  # Removed NPM_CONFIG_MAXSOCKETS to use default
  NIXPACKS_NODE_VERSION = "18"

[phases.setup]
  nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
  cmds = ["npm ci --omit=dev --omit=optional --prefer-offline --legacy-peer-deps"]

[phases.build]
  cmds = ["npm run build"]

[start]
cmd = "npx serve -s build -l $PORT -C"
