[phases.setup]
nixPkgs = ["python39", "nodejs-18_x"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd frontend && npm ci",
    "cd frontend && npm run build"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python ./api_server_prod.py"
override = true

[variables]
PORT = "8001"